services:
  api-gateway:
    build:
      context: ./api-gateway
      dockerfile: Dockerfile
    ports: [8080:8080]
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    networks:
      - meli-network

  inventory:
    build:
      context: ./inventory
      dockerfile: Dockerfile
    ports: [8081:8081]
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      - rabbitmq
    networks:
      - meli-network

  store:
    build:
      context: ./store
      dockerfile: Dockerfile
    ports: [8082:8082]
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      - rabbitmq
    networks:
      - meli-network

  rabbitmq:
    image: rabbitmq:3.12-management-alpine
    container_name: rabbitmq
    hostname: rabbitmq
    ports:
      - "5672:5672"      # AMQP port
      - "15672:15672"    # Management UI port
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - meli-network

volumes:
  rabbitmq_data:

networks:
  meli-network:
    driver: bridge